### ISSUE TITLE
请问下支持训练自己的音色吗？

### ISSUE THREAD

**Issue by zhaosinet** [THUDM/GLM-4-Voice#1]
感谢智谱开源，目前我在文档中没看到训练相关的用法，请问下支持训练自己的音色吗？

**Comment by RoversCode** [comment]
同问

**Comment by Sengxian** [comment]
可以通过微调 Flow Matching 模型的方式更换音色，现阶段可参考 CosyVoice 中的训练代码自行训练，后续可能会考虑开放 Flow Matching 的微调方法。
