### ISSUE TITLE
运行web_demo提示没有matcha.models

### ISSUE THREAD

**Issue by ydwasd** [THUDM/GLM-4-Voice#11]
/data/xxx/anaconda3/envs/glm-voice/lib/python3.10/site-packages/torch/_jit_internal.py:739: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
Traceback (most recent call last):
  File "/data/xxx/anaconda3/envs/glm-voice/lib/python3.10/pydoc.py", line 439, in safeimport
    module = __import__(path)
  File "/data/xxx/code/GLM-4-Voice-main/cosyvoice/flow/flow_matching.py", line 16, in <module>
    from matcha.models.components.flow_matching import BASECFM
ModuleNotFoundError: No module named 'matcha.models'; 'matcha' is not a package

**Comment by yaoao2017** [comment]
pip install matcha-tts

**Comment by Cupcc** [comment]
or `set PYTHONPATH=third_party/AcademiCodec;third_party/Matcha-TTS`

**Comment by indiejoseph** [comment]
> or `set PYTHONPATH=third_party/AcademiCodec;third_party/Matcha-TTS`

have to do `git submodule update --init --recursive` in the root first
