### ISSUE TITLE
云平台复现遇到的问题和解决方法记录

### ISSUE THREAD

**Issue by XksA-me** [THUDM/GLM-4-Voice#12]
## 0、环境问题 py3.12 下 numpy 编译出错

需要 python 3.10，
```bash
# 进入项目目录
cd GLM-4-Voice
# 安装依赖
conda create -n glm python=3.10
conda activate glm
pip install -r requirements.txt 
```

## 1、模型服务器启动找不到模型问题：

```bash
python model_server.py --model-pathglm-4-voice-9b
```
修改成：
```bash
python model_server.py --model-path THUDM/glm-4-voice-9b
```

## 2、FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'

```bash
apt update
apt install ffmpeg
```

## 3、默认 gradio 5.3 版本在某些情况不播放音频
降低版本解决了我的问题。
```bash
pip install gradio==4.44.1 
```

在云平台完整复现教程文档：https://blog.csdn.net/weixin_48344945/article/details/143236899

**Comment by zRzRzRzRzRzRzR** [comment]
升级到5.4.0 或者降级到4.44.1

**Comment by HelloLittleJoey** [comment]
pip install -r requirements.txt 
// 这一步一直报错呀，python 3.10/3.12都是这个问题，venv/conda都试过
