### ISSUE TITLE
Questions Regarding the Whisper Model

### ISSUE THREAD

**Issue by itsliupeng** [THUDM/GLM-4-Voice#13]
Congratulations, very good work.

Is GLM-4-Voice utilizing the whisper-large encoder? If so, why does it employ only 16 layers, whereas the whisper-large model consists of 32 layers?

Furthermore, could you clarify why GLM-4-Voice adopts CausalConv1d rather than aligning with the standard convolution (Conv) used in the whisper model?

**Comment by duzx16** [comment]
The tokenizer is fine-tuned from whisper-large-v3. The reason why it employs only 16 layers is that we add the vector quantization layer in the middle of the encoder.

We use CausalConv1d because we want the tokenizer to be causal to support streaming inference of input speech.
