### ISSUE TITLE
GLM-4-Voice报错

### ISSUE THREAD

**Issue by xiazhi-wfd** [THUDM/GLM-4-Voice#132]
[出错.pdf](https://github.com/user-attachments/files/18090689/default.pdf)
我们使用的是Windows操作系统
1、将main、glm-4-voice-9b、glm-4-voice-decoder、glm-4-voice-tokenizer下载到了本地
2、安装了conda，创建了虚拟环境voice，安装了pynini2.1.6和WeTextProcessing1.0.4
3、在虚拟环境执行了pip install requirements
4、安装了matcha-tts到本机
5、执行了智普大模型，python model_server.py --host localhost --model-path ../glm-4-voice-9b --port 10000 --dtype bfloat16 --device cpu，这一步没有报错，正常结束
6、执行了下一步，python web_demo.py --tokenizer-path  ../glm-4-voice-tokenizer --model-path ../glm-4-voice-9b --flow-path ../glm-4-voice-decoder，更新了gradio版本，返回了前端结果，将main中的deice由cuda改为了cpu
7、在前端打开界面127.0.0.1:8888，输入文字或语音提交之后，出现如文件中的错误，错误显示目标计算机积极拒接，无法连接

**Comment by sixsixcoder** [comment]
可以修改版本gradio==4.44.1，另外，cpu上估计不能完美运行
