### ISSUE TITLE
不能复现对论文里对moshi的评测

### ISSUE THREAD

**Issue by UltraEval** [THUDM/GLM-4-Voice#141]
感谢开源👍🏻

在论文《Scaling speech-text pre-training with synthetic interleaved data》里
对moshi的评测，

![image](https://github.com/user-attachments/assets/de788cb4-a159-4698-bb72-4a29723dd4b9)
其他模型的评测结果都可以复现，但是无法复现Moshi这个评测，可以分享下Moshi的推理吗？🙏🙏🙏

**Comment by tianzhangwu** [comment]
请问你这里测试时，输入音频是采用什么TTS工具合成的呢呢？不同TTS工具分数也会不同。

**Comment by UltraEval** [comment]
> 请问你这里测试时，输入音频是采用什么TTS工具合成的呢呢？不同TTS工具分数也会不同。

火山引擎seed TTS

我现在推理时，moshi基本上只回复“How are you”类似的开场白，偶尔能在开场白之后正式回复

**Comment by tianzhangwu** [comment]
我这里尝试用meloTTS和chattts分别测试过开源出来的GLM-4-voice，比他们论文里的结果要高一些，比技术报告里的分数要低。在4.5分上下。

Moshi我还没测过，不过之前看过知乎的讨论，这个模型经常不能正常回答问题。这里的现象看起来是prompt mismatch了。

**Comment by tianzhangwu** [comment]
不知道你有没有测试过开源出来的GLM-4-voice的效果？

**Comment by UltraEval** [comment]
> 不知道你有没有测试过开源出来的GLM-4-voice的效果？

复现了，和论文里的结果基本一致

**Comment by tianzhangwu** [comment]
指的是3.69这个指标吗？

**Comment by tianzhangwu** [comment]
他们技术报告的结果是5.40，不知道你这里复现出来更接近哪一个啊
<img width="792" alt="image" src="https://github.com/user-attachments/assets/5ca13470-48aa-4600-9e7c-274c92abb73b" />

**Comment by UltraEval** [comment]
> 我这里尝试用meloTTS和chattts分别测试过开源出来的GLM-4-voice，比他们论文里的结果要高一些，比技术报告里的分数要低。在4.5分上下。
> 
> Moshi我还没测过，不过之前看过知乎的讨论，这个模型经常不能正常回答问题。这里的现象看起来是prompt mismatch了。

Moshi 的推理好像有些问题，我之前要给他们提过issue, 还没有官方回复，有人说开源和论文里的不一样https://github.com/kyutai-labs/moshi/issues/159

**Comment by UltraEval** [comment]
> 他们技术报告的结果是5.40，不知道你这里复现出来更接近哪一个啊 <img alt="image" width="792" src="https://private-user-images.githubusercontent.com/187403976/398526973-5ca13470-48aa-4600-9e7c-274c92abb73b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMDkxMTYsIm5iZiI6MTczNTEwODgxNiwicGF0aCI6Ii8xODc0MDM5NzYvMzk4NTI2OTczLTVjYTEzNDcwLTQ4YWEtNDYwMC05ZTdjLTI3NGM5MmFiYjczYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQwNjQwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTUzYTU3NGQ1ODNlZmI5NDhmZjFiOWQwMDA2ZDk5NDgxMzFiYWFkNmU0ODdkY2QyZTFlOTdiNDdmYzUxMmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g3GooNjnkMBfHoHiRub8cuC6o-mhLxSgly7P5ZLc8B8">

是5.4这个，前面的Speech2Text虽然论文里是用Base模型，我使用开源的chat模型结果也差不多

**Comment by tianzhangwu** [comment]
谢谢，我估计可能是这个细节没对齐：
For a fair comparison with the English-only baseline models, we restrict the output of GLM-4-Voice to English tokens when evaluating the tasks reported in Table 6. 

实测确实发现不少问英文，回答中文的case。

**Comment by UltraEval** [comment]
> 谢谢，我估计可能是这个细节没对齐： For a fair comparison with the English-only baseline models, we restrict the output of GLM-4-Voice to English tokens when evaluating the tasks reported in Table 6.
> 
> 实测确实发现不少问英文，回答中文的case。

这个情况我在review case的时候发现了，但是论文里的这个限制有点不合理，不过也无伤大雅。
这里的Knowledge也无法复现，因为是随机了100个数据；
UTMOS的测试llama-omni和论文里对不上，这里的有可能是使用音频数据问题，不过听了下Llama-Omni的音频问题还是很明显的生硬停顿，不知道为什么这么高分

**Comment by Btlmd** [comment]
> 我现在推理时，moshi基本上只回复“How are you”类似的开场白，偶尔能在开场白之后正式回复

这个我们会给 Moshi 的评测输入前拼接 3 秒的全空白输入，让 Moshi 完成开场白之后再提问

> Moshi is fine-tuned for full duplex conversations and each conversation must begin with a greeting from
the model. Therefore, we wait 3 seconds for the greeting to end before asking the speech query. (Section 3.1)

**Comment by UltraEval** [comment]
> > 我现在推理时，moshi基本上只回复“How are you”类似的开场白，偶尔能在开场白之后正式回复
> 
> 这个我们会给 Moshi 的评测输入前拼接 3 秒的全空白输入，让 Moshi 完成开场白之后再提问
> 
> > Moshi is fine-tuned for full duplex conversations and each conversation must begin with a greeting from
> > the model. Therefore, we wait 3 seconds for the greeting to end before asking the speech query. (Section 3.1)

🙏🙏这个方法我也尝试过，但是输出还是只有开场白，你们使用的推理代码是 moshi/moshi/readme.md里吗？还是moshi/moshi/service.py?
![image](https://github.com/user-attachments/assets/4a00aa96-baea-4084-9156-e1f45d35ef4e)

**Comment by Btlmd** [comment]
我们的代码是修改了 commit d654de31 中 `moshi/moshi/server.py` 的 `ServerState.handle_chat` 接口，直接在用户已有输入的基础上拼接了 3s 长度的空白音频

**Comment by UltraEval** [comment]
发现使用拼接前面空白不够，还是需要在音频后面拼接空白

```python
    def encode(self, audio_path):
        print(self.mimi.sample_rate)
        wav = load_wav(audio_path, self.mimi.sample_rate)
        current_length = wav.shape[-1]
        target_length = ((current_length - 1) // 1920 + 1) * 1920
        if current_length < target_length:
            # 如果长度不足，以零填充至目标长度
            padding = target_length - current_length
            wav = torch.nn.functional.pad(wav, (0, padding))
        wav = torch.nn.functional.pad(wav, (1920 * 50, 1920 * 100))
        wav = wav.unsqueeze(0)  # [B, T]
```
