### ISSUE TITLE
No such file or directory: './glm-4-voice-decoder/config.yaml'

### ISSUE THREAD

**Issue by sabibi12** [THUDM/GLM-4-Voice#18]
![image](https://github.com/user-attachments/assets/6bf77a15-0d43-4d1d-9f85-9b5962aac79b)

H100部署时出现问题

`root@grown-orchid-hummingbird:~/GLM-4-Voice# ls
LICENSE  README.md  README_en.md  __pycache__  cosyvoice  flow_inference.py  glm-4-Voice-decoder  model_server.py  requirements.txt  resources  speech_tokenizer  third_party  web_demo.py
root@grown-orchid-hummingbird:~/GLM-4-Voice# python3 web_demo.py
Traceback (most recent call last):
  File "/root/GLM-4-Voice/web_demo.py", line 253, in <module>
    initialize_fn()
  File "/root/GLM-4-Voice/web_demo.py", line 54, in initialize_fn
    audio_decoder = AudioDecoder(config_path=flow_config, flow_ckpt_path=flow_checkpoint,
  File "/root/GLM-4-Voice/flow_inference.py", line 23, in __init__
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './glm-4-voice-decoder/config.yaml'
root@grown-orchid-hummingbird:~/GLM-4-Voice# `

**Comment by fanlu** [comment]
```
python web_demo.py --model-path ../glm-4-voice-9b --tokenizer-path ../glm-4-voice-tokenizer/ --flow-path ../glm-4-voice-decoder/
```

**Comment by duzx16** [comment]
Since CosyVoice doesn't support loading models from huggingface, you need to manually download https://huggingface.co/THUDM/glm-4-voice-decoder into the GLM-4-Voice directory.
