### ISSUE TITLE
可以提供一个Docker镜像吗？

### ISSUE THREAD

**Issue by log4gin** [THUDM/GLM-4-Voice#47]
大佬，我在我的 mac 上的 docker ubuntu环境 安装依赖的时候报错。
但是我却不知道怎么处理。🙏求指点。
<img width="1624" alt="截屏2024-10-29 10 11 08" src="https://github.com/user-attachments/assets/00530cae-3631-4e49-aa43-b88990f093fb">

**Comment by duzx16** [comment]
zhipuai/glm-4-voice:0.1
