### ISSUE TITLE
执行python web_demo.py 报错

### ISSUE THREAD

**Issue by njzfw1024** [THUDM/GLM-4-Voice#53]
![image](https://github.com/user-attachments/assets/e2318c70-28d2-4991-9733-0cad95cae6c7)

**Comment by njzfw1024** [comment]
> 是不是python版本太老了，试试dev现在的依赖，用python3.10 或者pyhton3.12

好的

**Comment by candlewill** [comment]
python 3.12是不支持的，python 3.11可以
