### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by zcdliuwei** [THUDM/GLM-4-Voice#59]
非常棒的开源项目，支持国产，加油！
我还没有部署使用，看了介绍和大家的讨论，有两个问题希望能得到作者的解答：
1，如何支持其他语种，比如法语、日语等；
2，如何支持自定义音色，比如我想用自己的声音，来生成某种情感的、某种语速的语音。
应该是需要自己微调预训练模型、以及训练其他音色等。我看您的仓库目前还没有训练及微调部分，请问会考虑发布微调代码，以支持上述两种自定义需求吗
期待您的回复

**Comment by zRzRzRzRzRzRzR** [comment]
目前确实没有微调部分，是因为目前声音和语言模型耦合比较严重，微调的话成本非常高，同时，也非常的需要优质数据集。一般开发者很难完成高质量数据集的构建，进行二次定制

**Comment by zcdliuwei** [comment]
您好，再请问一下，想要运行gradio UI页面，必须先执行：python model_server.py --host localhost --model-path THUDM/glm-4-voice-9b --port 10000 --dtype bfloat16 --device cuda:0
不能打断它，然后同时运行：python web_demo.py --tokenizer-path  THUDM/glm-4-voice-tokenizer --model-path THUDM/glm-4-voice-9b --flow-path ./glm-4-voice-decoder吗

另外，这两个命令host和port参数如何设置，需要使用相同的参数吗

**Comment by svmlearn** [comment]
> 您好，再请问一下，想要运行gradio UI页面，必须先执行：python model_server.py --host localhost --model-path THUDM/glm-4-voice-9b --port 10000 --dtype bfloat16 --device cuda:0 不能打断它，然后同时运行：python web_demo.py --tokenizer-path THUDM/glm-4-voice-tokenizer --model-path THUDM/glm-4-voice-9b --flow-path ./glm-4-voice-decoder吗
> 
> 另外，这两个命令host和port参数如何设置，需要使用相同的参数吗

你需要在不同的终端去运行这两个命令。以autodl为例子，在一个终端运行python model_server.py 
新起一个终端，运行web_demo就可以了
我使用的：
python model_server.py --host 0.0.0.0 --port 10000 --dtype int4 --device cuda:0
python web_demo.py --host0.0.0.0 --port 7860

**Comment by zcdliuwei** [comment]
> > 您好，再请问一下，想要运行gradio UI页面，必须先执行：python model_server.py --host localhost --model-path THUDM/glm-4-voice-9b --port 10000 --dtype bfloat16 --device cuda:0 不能打断它，然后同时运行：python web_demo.py --tokenizer-path THUDM/glm-4-voice-tokenizer --model-path THUDM/glm-4-voice-9b --flow-path ./glm-4-voice-decoder吗
> > 另外，这两个命令host和port参数如何设置，需要使用相同的参数吗
> 
> 你需要在不同的终端去运行这两个命令。以autodl为例子，在一个终端运行python model_server.py 新起一个终端，运行web_demo就可以了 我使用的： python model_server.py --host 0.0.0.0 --port 10000 --dtype int4 --device cuda:0 python web_demo.py --host0.0.0.0 --port 7860

明白了，谢谢您的回复
我之前都是执行完第一个命令就中断了它，所以第二个就执行不了。
我现在把第一个命令使用默认host和port，第二个命令把host改成了自己的本地地址，可以运行了。
不过感觉作者代码可能存在问题，因为我输入文本，比如：用广东话念XXX，输出的音频是普通话，需要刷新页面，或者点击clear后再执行，才会变成广东话，可能有缓存问题

**Comment by svmlearn** [comment]
哦哦，那个好像要下一个包。作者少给了一个，你看下其他人的提问和回答，有一个标题叫做“扫坑”。里面有一些避坑指南

---- 回复的原邮件 ----
| 发件人 | Keep Growing And Moving ***@***.***> |
| 发送日期 | 2024年11月04日 18:15 |
| 收件人 | THUDM/GLM-4-Voice ***@***.***> |
| 抄送人 | svmlearn ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [THUDM/GLM-4-Voice] 请教 (Issue #59) |

您好，再请问一下，想要运行gradio UI页面，必须先执行：python model_server.py --host localhost --model-path THUDM/glm-4-voice-9b --port 10000 --dtype bfloat16 --device cuda:0 不能打断它，然后同时运行：python web_demo.py --tokenizer-path THUDM/glm-4-voice-tokenizer --model-path THUDM/glm-4-voice-9b --flow-path ./glm-4-voice-decoder吗
另外，这两个命令host和port参数如何设置，需要使用相同的参数吗

你需要在不同的终端去运行这两个命令。以autodl为例子，在一个终端运行python model_server.py 新起一个终端，运行web_demo就可以了 我使用的： python model_server.py --host 0.0.0.0 --port 10000 --dtype int4 --device cuda:0 python web_demo.py --host0.0.0.0 --port 7860

明白了，谢谢您的回复
我之前都是执行完第一个命令就中断了它，所以第二个就执行不了。
我现在把第一个命令使用默认host和port，第二个命令把host改成了自己的本地地址，可以运行了。
不过感觉作者代码可能存在问题，因为我输入文本，比如：用广东话念XXX，输出的音频是普通话，需要刷新页面，或者点击clear后再执行，才会变成广东话，可能有缓存问题

**Comment by zcdliuwei** [comment]
> 哦哦，那个好像要下一个包。作者少给了一个，你看下其他人的提问和回答，有一个标题叫做“扫坑”。里面有一些避坑指南
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Keep Growing And Moving ***@***.***> | | 发送日期 | 2024年11月04日 18:15 | | 收件人 | THUDM/GLM-4-Voice ***@***.***> | | 抄送人 | svmlearn ***@***.***>, Comment ***@***.***> | | 主题 | Re: [THUDM/GLM-4-Voice] 请教 (Issue #59) | 您好，再请问一下，想要运行gradio UI页面，必须先执行：python model_server.py --host localhost --model-path THUDM/glm-4-voice-9b --port 10000 --dtype bfloat16 --device cuda:0 不能打断它，然后同时运行：python web_demo.py --tokenizer-path THUDM/glm-4-voice-tokenizer --model-path THUDM/glm-4-voice-9b --flow-path ./glm-4-voice-decoder吗 另外，这两个命令host和port参数如何设置，需要使用相同的参数吗 你需要在不同的终端去运行这两个命令。以autodl为例子，在一个终端运行python model_server.py 新起一个终端，运行web_demo就可以了 我使用的： python model_server.py --host 0.0.0.0 --port 10000 --dtype int4 --device cuda:0 python web_demo.py --host0.0.0.0 --port 7860 明白了，谢谢您的回复 我之前都是执行完第一个命令就中断了它，所以第二个就执行不了。 我现在把第一个命令使用默认host和port，第二个命令把host改成了自己的本地地址，可以运行了。 不过感觉作者代码可能存在问题，因为我输入文本，比如：用广东话念XXX，输出的音频是普通话，需要刷新页面，或者点击clear后再执行，才会变成广东话，可能有缓存问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

感谢回复，我去看看
