### ISSUE TITLE
请教，dev分支的requirement vllm0.6.4是预计下个版本支持GLM4voice吗？

### ISSUE THREAD

**Issue by Jimmy-L99** [THUDM/GLM-4-Voice#74]
在找glm4-voice关于vllm的代码，发现dev分支里面有关于vllm的api，但为啥是0.6.4，看到vllm仓库最新是0.6.3post1。
https://github.com/THUDM/GLM-4-Voice/blob/37cf04931181f6363936bd5184799168758381b5/requirements.txt#L26-L26

**Comment by sixsixcoder** [comment]
是的，我们后续会支持vllm最新版本

**Comment by sixsixcoder** [comment]
目前dev分支已经支持vllm 0.6.3post1，您可以下载体验
