### ISSUE TITLE
所有的推理出的音频内容无法在gradio的audio控件播放

### ISSUE THREAD

**Issue by codersun123** [THUDM/GLM-4-Voice#76]
在gradio版本5.3.0与5.5.0中推理出的音频内容无法播放，时长为0
请问是什么问题，有人碰到类似的问题了吗？如何解决
![1](https://github.com/user-attachments/assets/cdd52053-6909-47c5-8b15-199e4efb50cf)
![2](https://github.com/user-attachments/assets/b5226bd1-e961-4341-8429-3223d6fd9e39)

我现在是通过指定音频保存路径来确认音频生成结果的
with tempfile.NamedTemporaryFile(suffix=".wav", delete=False,dir="/root/autodl-tmp/temp") as f:
            print(f"111:{f.name}")
            torchaudio.save(f, tts_speech.unsqueeze(0), 22050, format="wav")

**Comment by sixsixcoder** [comment]
可以试一下gradio==4.44.1

**Comment by codersun123** [comment]
感谢你的帮助，改成这个版本以后，流式返回这个播放正常了，但是最终生成的和chatbot里的audio控件还是一样

> 可以试一下gradio==4.44.1

**Comment by LiuKai22** [comment]
@codersun123 @sixsixcoder  请问你解决这个问题了吗？我也遇到相似的问题，也是AutoDL的机器环境。

**Comment by sixsixcoder** [comment]
> @codersun123 @sixsixcoder 请问你解决这个问题了吗？我也遇到相似的问题，也是AutoDL的机器环境。

可以试一下gradio==4.44.1

**Comment by codersun123** [comment]
> @codersun123 @sixsixcoder 请问你解决这个问题了吗？我也遇到相似的问题，也是AutoDL的机器环境。

只有流式音频内容是正常的，其它的audio都不能关联到正确的wav文件

**Comment by Zuckonit** [comment]
还是不行
