### ISSUE TITLE
你可以先输入“请帮我把下列这段维吾尔语翻译成中文”的语音，提交问答后，再输入你想要翻译的维吾尔语

### ISSUE THREAD

**Issue by Yopoto** [THUDM/GLM-4-Voice#83]
你可以先输入“请帮我把下列这段维吾尔语翻译成中文”的语音，提交问答后，再输入你想要翻译的维吾尔语
<img width="908" alt="image" src="https://github.com/user-attachments/assets/d71bb357-c6fb-430d-a1e2-aea9f65fcfab">

_Originally posted by @sixsixcoder in https://github.com/THUDM/GLM-4-Voice/issues/77#issuecomment-2464197405_

**Comment by sixsixcoder** [comment]
请问您的问题是什么
