### ISSUE TITLE
Whether the training dataset will be made public

### ISSUE THREAD

**Issue by SteinsHead** [THUDM/GLM-4-Voice#87]
First of all, thank you very much for your work—GLM-4-Voice is an impressive end-to-end speech model. I’d like to ask if you plan to release the training datasets, including those for GLM-4-Voice-Tokenizer, GLM-4-Voice-Decoder, and GLM-4-Voice-9B, as well as the training scripts.

**Comment by sixsixcoder** [comment]
You can follow the detailed technical report released later

**Comment by SteinsHead** [comment]
Okay, thank you again for your work, it has been very helpful to me!
